version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "${POSTGRES_PORT:-5789}:5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025:1025", "1082:1080"]
###< symfony/mailer ###
